const express = require('express');
const { getLeaderboard, getAgentRanking } = require('../persistence');

const router = express.Router();

// In-house named agents with their roles (must match demo.js)
const NAMED_AGENTS = {
  // Attackers
  BlitzRunner: 'attacker',
  IronWall: 'attacker',
  Spectre: 'attacker',
  // Defenders
  Sentinel: 'defender',
  Fortress: 'defender',
  Striker: 'defender',
  Guardian: 'defender'
};

// Pattern to detect auto-generated demo agent names (e.g., attacker_3_1770099697601, demo_back-heavy_1770093074723)
const AUTO_GENERATED_PATTERN = /^(attacker|defender|demo|batch)_.*_\d{10,}$/;

/**
 * Check if an agent ID is an auto-generated demo name
 */
function isAutoGeneratedDemo(agentId) {
  return AUTO_GENERATED_PATTERN.test(agentId);
}

/**
 * GET /leaderboard
 * Get top agents sorted by ELO
 * Excludes auto-generated demo agents by default (keeps in-house + external bots)
 *
 * Query params:
 *   limit: number (1-100, default 50)
 *   include_auto: boolean (if true, include auto-generated demo agents)
 */
router.get('/', (req, res) => {
  const limit = Math.min(Math.max(parseInt(req.query.limit) || 50, 1), 100);
  const includeAuto = req.query.include_auto === 'true';

  // Get all rankings
  let leaderboard = getLeaderboard(1000);

  // Exclude auto-generated demo agents by default (keep in-house named agents)
  if (!includeAuto) {
    leaderboard = leaderboard.filter(entry => !isAutoGeneratedDemo(entry.agentId));
  }

  const totalAgents = leaderboard.length;

  // Add role information to each entry
  leaderboard = leaderboard.map(entry => ({
    ...entry,
    role: NAMED_AGENTS[entry.agentId] || 'external',
    isInHouse: !!NAMED_AGENTS[entry.agentId]
  }));

  // Apply limit and re-rank
  leaderboard = leaderboard.slice(0, limit).map((entry, index) => ({
    ...entry,
    rank: index + 1
  }));

  res.json({
    totalAgents,
    totalRanked: leaderboard.length,
    leaderboard
  });
});

/**
 * GET /leaderboard/:agentId
 * Get detailed ranking info for a specific agent
 */
router.get('/:agentId', (req, res) => {
  const { agentId } = req.params;
  const ranking = getAgentRanking(agentId);

  if (!ranking) {
    return res.status(404).json({
      error: 'Agent not found',
      message: `No ranking data for agent: ${agentId}`
    });
  }

  // Add role information
  ranking.role = NAMED_AGENTS[agentId] || 'unknown';

  res.json(ranking);
});

module.exports = router;
